### ISSUE TITLE
It isn't clear.

### ISSUE THREAD

**Issue by HemyO** [mmatongo/vscode-abyss#2]
This Abyss is really dark that help me and my mates.
But I think the color of Modifiers ( like public, private ... ), Value Types (int, float, double ...) and Method is too close to the background color.
Maybe It can increase gray scale to make it clear.

This one is C# with Unity
![Capture](https://user-images.githubusercontent.com/67676350/90515487-51626100-e195-11ea-8ab8-644bfee30ac0.PNG)
This one is Java
![01](https://user-images.githubusercontent.com/67676350/90515508-59ba9c00-e195-11ea-8757-284b3b8809ee.PNG)

**Comment by mmatongo** [comment]
Alright, I'm recreating the whole theme from scratch so I'll do this.

**Comment by HemyO** [comment]
Thx for replying !! :)

**Comment by mmatongo** [comment]
The theme has somewhat been redone and I've pushed an update to the marketplace.
This is fixed, check the changelog.
